---



name: Deploy to Stagnet and Testnet

"on":
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/deploy.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:

  deploy:
    name: Deploy to Stagnet/Testnet
    runs-on: ubuntu-latest

    env:
      MONGO_SECRET_NAME: projects/${{ secrets.GCP_PROJECT_ID }}/secrets/${{ secrets.SMV_GCP_MONGO_SECRET_NAME }}/versions/latest
      TWITTER_SECRET_NAME: projects/${{ secrets.GCP_PROJECT_ID }}/secrets/${{ secrets.SMV_GCP_TWITTER_SECRET_NAME }}/versions/latest
      TWITTER_SEARCH_TEXT: I'm taking a ride on
      TWITTER_REPLY_SUCCESS: Thanks for joining!
      TWITTER_REPLY_INVALID_FORMAT: The format of your Tweet is invalid. Please see https://fairground.wtf/how-to-register-for-incentives for troubleshooting tips.
      TWITTER_REPLY_INVALID_SIGNATURE: The signature in your Tweet is invalid. Please see https://fairground.wtf/how-to-register-for-incentives for troubleshooting tips.

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish to Stagnet and Testnet
        uses: google-github-actions/deploy-cloud-functions@main
        id: deploy
        with:
          name: smv
          runtime: python39
          entry_point: router
          memory_mb: 512MB
          region: ${{ secrets.SMV_GCP_REGION }}
          credentials: ${{ secrets.SMV_GCP_SA_KEY }}
          env_vars: MONGO_SECRET_NAME=${{ env.MONGO_SECRET_NAME }},TWITTER_SECRET_NAME=${{ env.TWITTER_SECRET_NAME }},TWITTER_SEARCH_TEXT=${{ env.TWITTER_SEARCH_TEXT }},TWITTER_REPLY_SUCCESS=${{ env.TWITTER_REPLY_SUCCESS }},TWITTER_REPLY_INVALID_FORMAT=${{ env.TWITTER_REPLY_INVALID_FORMAT }},TWITTER_REPLY_INVALID_SIGNATURE=${{ env.TWITTER_REPLY_INVALID_SIGNATURE }}
          source_dir: src
          description: Social Media Verification
          service_account_email: ${{ secrets.SMV_GCP_SA_EMAIL }}

      - name: Test deployed service
        run: curl "${{ steps.deploy.outputs.url }}/parties"
