---

name: Python tests

"on":
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:

  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit tests
        run: make test-in-docker-compose
